name: Output information
on: issues
jobs:
  og_issue_info:
    runs-on: ubuntu-latest
    steps:
    - name: Get Issue Information
      id: get_issue_info
      run: |
        echo "Issue Title: ${{ toJSON(github.event.issue.title) }}"
        echo "Issue Body: ${{ toJSON(github.event.issue.body) }}"
        echo "Issue Number: ${{ toJSON(github.event.issue.number) }}"
        echo "Issue URL: ${{ toJSON(github.event.issue.html_url) }}"
    - name: Log Issue Information
      run: |
        echo "Issue Information: ${{ toJSON(steps.get_issue_info.outputs.text) }}"




